const ActionTypes = {
  ADD_TODO: 'ADD_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  TOGGLE_TODO: 'TOGGLE_TODO',
  FETCHING_POSTS_PENDING: 'FETCHING_POSTS_PENDING',
  FETCHING_POSTS_REJECTED: 'FETCHING_POSTS_REJECTED',
  RECEIVE_TAGS: 'RECEIVE_TAGS',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RESET_DASHBOARD_STATUS: 'RESET_DASHBOARD_STATUS',
  RECEIVE_USER: 'RECEIVE_USER',
  FETCHING_USER_PENDING: 'FETCHING_USER_PENDING',
  FETCHING_USER_REJECTED: 'FETCHING_USER_REJECTED',
  INPUT_CHANGE: 'INPUT_CHANGE',
  SUBMIT_FORM: 'SUBMIT_FORM',
  RECEIVE_POST: 'RECEIVE_POST',
  FETCHING_POST_PENDING: 'FETCHING_POST_PENDING',
  FETCHING_POST_REJECTED: 'FETCHING_POST_REJECTED',
  RECEIVE_POST_COMMENTS: 'RECEIVE_POST_COMMENTS',
  FETCHING_POST_COMMENTS_PENDING: 'FETCHING_POST_COMMENTS_PENDING',
  FETCHING_POST_COMMENTS_REJECTED: 'FETCHING_POST_COMMENTS_REJECTED',
  FOLLOW_POST: 'FOLLOW_POST',
  UNFOLLOW_POST: 'UNFOLLOW_POST',
  LOG_OUT: 'LOG_OUT',
  LOGIN_MODAL_OPEN: 'LOGIN_MODAL_OPEN',
  LOGIN_MODAL_CLOSE: 'LOGIN_MODAL_CLOSE'
}

export default ActionTypes