const ActionTypes = {
  ADD_TODO: 'ADD_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  TOGGLE_TODO: 'TOGGLE_TODO',
  FETCHING_POSTS_PENDING: 'FETCHING_POSTS_PENDING',
  FETCHING_POSTS_REJECTED: 'FETCHING_POSTS_REJECTED',
  RECEIVE_TAGS: 'RECEIVE_TAGS',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RECEIVE_USER: 'RECEIVE_USER',
  FETCHING_USER_PENDING: 'FETCHING_USER_PENDING',
  FETCHING_USER_REJECTED: 'FETCHING_USER_REJECTED',
  INPUT_CHANGE: 'INPUT_CHANGE',
  SUBMIT_FORM: 'SUBMIT_FORM',
  RECEIVE_POST: 'RECEIVE_POST',
  FETCHING_POST_PENDING: 'FETCHING_POST_PENDING',
  FETCHING_POST_REJECTED: 'FETCHING_POST_REJECTED',
  RECEIVE_POST_COMMENTS: 'RECEIVE_POST_COMMENTS',
  FETCHING_POST_COMMENTS_PENDING: 'FETCHING_POST_COMMENTS_PENDING',
  FETCHING_POST_COMMENTS_REJECTED: 'FETCHING_POST_COMMENTS_REJECTED',
  FOLLOW_POST: 'FOLLOW_POST',
  UNFOLLOW_POST: 'UNFOLLOW_POST',
  LOG_OUT: 'LOG_OUT',
  LOGIN_MODAL_OPEN: 'LOGIN_MODAL_OPEN',
  LOGIN_MODAL_CLOSE: 'LOGIN_MODAL_CLOSE',
  // Post searching
  FETCHING_SEARCHING_POST_PENDING: 'FETCHING_SEARCHING_POST_PENDING',
  RECEIVE_SEARCHING_POST: 'RECEIVE_SEARCHING_POST',
  FETCHING_SEARCHING_POST_REJECTED: 'FETCHING_SEARCHING_POST_REJECTED',
  // Notifications
  FETCHING_NOTIFICATIONS_PENDING: 'FETCHING_NOTIFICATIONS_PENDING',
  RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',
  FETCHING_NOTIFICATIONS_REJECTED: 'FETCHING_NOTIFICATIONS_REJECTED',
  // User card info
  FETCHING_USER_CARD_INFO_PENDING: 'FETCHING_USER_CARD_INFO_PENDING',
  RECEIVE_USER_CARD_INFO: 'RECEIVE_USER_CARD_INFO',
  FETCHING_USER_CARD_INFO_REJECTED: 'FETCHING_USER_CARD_INFO_REJECTED',
  TOGGLE_VISIBILITY: 'TOGGLE_VISIBILITY',

  LIKE_COMMENT_SUCCESS: 'LIKE_COMMENT_SUCCESS',
  LIKE_COMMENT_FAILURE: 'LIKE_COMMENT_FAILURE',
  TAG_SELECT: 'TAG_SELECT',

  OPEN_IMAGE_MODAL: 'OPEN_IMAGE_MODAL',
  CLOSE_IMAGE_MODAL: 'CLOSE_IMAGE_MODAL',

  ADD_IMAGE: 'ADD_IMAGE',
  DELETE_IMAGE: 'DELETE_IMAGE',
  POST_TITLE_CHANGED: 'POST_TITLE_CHANGED',
  POST_BODY_CHANGED: 'POST_BODY_CHANGED',
  NEW_POST_PENDING: 'NEW_POST_PENDING',
  NEW_POST_SUCCESS: 'NEW_POST_SUCCESS',
  NEW_POST_FAILURE: 'NEW_POST_FAILURE'

}

export default ActionTypes